version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./src/WorkTimeManager.Web/Dockerfile
    ports:
      - "5000:80"
      - "5050:5050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Debug
      - JWT_SECURITY_KEY=
      - MAIN_DB=User ID=
      - SECURITY_DB=User ID=